import { AiOutlineRight } from 'react-icons/ai';
export const data = [
  {
    id: 1,
    title: 'Phone and Electronics',
  },
  {
    id: 2,
    title: 'Phone and Electronics',
  },
  {
    id: 3,
    title: 'Best Seller',
    icon2: <AiOutlineRight />,
    subMenu: [
      {
        id: 1,
        subTitle: 'Tittle One',
        items: [
          { id: 1, text: 'Listing One' },
          { id: 2, text: 'Listing Two' },
          { id: 3, text: 'Listing Three' },
          { id: 4, text: 'Listing Four' },
          { id: 5, text: 'Listing Five' },
        ],
      },
      {
        id: 2,
        subTitle: 'Tittle Two',
        items: [
          { id: 1, text: 'Listing One' },
          { id: 2, text: 'Listing Two' },
          { id: 3, text: 'Listing Three' },
          { id: 4, text: 'Listing Four' },
          { id: 5, text: 'Listing Five' },
        ],
      },
      {
        id: 3,
        subTitle: 'Tittle Three',
        items: [
          { id: 1, text: 'Listing One' },
          { id: 2, text: 'Listing Two' },
          { id: 3, text: 'Listing Three' },
          { id: 4, text: 'Listing Four' },
          { id: 5, text: 'Listing Five' },
        ],
      },
      {
        id: 4,
        subTitle: 'Tittle Four',
        items: [
          { id: 1, text: 'Listing One' },
          { id: 2, text: 'Listing Two' },
          { id: 3, text: 'Listing Three' },
          { id: 4, text: 'Listing Four' },
          { id: 5, text: 'Listing Five' },
        ],
      },
      {
        id: 5,
        subTitle: 'Tittle Five',
        items: [
          { id: 1, text: 'Listing One' },
          { id: 2, text: 'Listing Two' },
          { id: 3, text: 'Listing Three' },
          { id: 4, text: 'Listing Four' },
          { id: 5, text: 'Listing Five' },
        ],
      },
    ],
  },
  {
    id: 4,
    title: 'Top 10 Offers',
    icon2: <AiOutlineRight />,
    product: 'product',
    items: [
      {
        id: 1,
        subTitle: 'items Tittle',
        image: '/images/featured2.jpg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
      {
        id: 2,
        subt: 'items Tittle',
        image: '/images/featured2.jpg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
      {
        id: 3,
        subTitle: 'items Tittle',
        image: '/images/featured3.jpeg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
      {
        id: 4,
        subTitle: 'items Tittle',
        image: '/images/featured4.jpeg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
      {
        id: 5,
        subTitle: 'items Tittle',
        image: '/images/featured5.jpeg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
      {
        id: 6,
        subTitle: 'items Tittle',
        image: '/images/featured2.jpg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
      {
        id: 7,
        subTitle: 'items Tittle',
        image: '/images/featured4.jpeg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
      {
        id: 8,
        subTitle: 'items Tittle',
        image: '/images/featured5.jpeg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
      {
        id: 9,
        subTitle: 'items Tittle',
        image: '/images/featured3.jpeg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
      {
        id: 10,
        subTitle: 'items Tittle',
        image: '/images/featured4.jpeg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
    ],
  },
  {
    id: 5,
    title: 'TV & Audio',
    icon2: <AiOutlineRight />,
    product: 'product',
    items: [
      {
        id: 1,
        subTitle: 'items Title',
        image: '/images/featured2.jpg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
      {
        id: 2,
        subTitle: 'items Title',
        image: '/images/featured2.jpg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
      {
        id: 3,
        subTitle: 'items Title',
        image: '/images/featured3.jpeg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
      {
        id: 4,
        subTitle: 'items Title',
        image: '/images/featured4.jpeg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
      {
        id: 5,
        subTitle: 'items Title',
        image: '/images/featured5.jpeg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
      {
        id: 6,
        subTitle: 'items Title',
        image: '/images/featured2.jpg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
      {
        id: 7,
        subTitle: 'items Title',
        image: '/images/featured4.jpeg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
      {
        id: 8,
        subTitle: 'items Title',
        image: '/images/featured5.jpeg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
      {
        id: 9,
        subTitle: 'items Title',
        image: '/images/featured3.jpeg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
      {
        id: 10,
        subTitle: 'items Title',
        image: '/images/featured4.jpeg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
    ],
  },
  {
    id: 6,
    title: 'Key Board',
    icon2: <AiOutlineRight />,
    product: 'product',
    items: [
      {
        id: 1,
        subTitle: 'items Title',
        image: '/images/featured2.jpg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
      {
        id: 2,
        subTitle: 'items Title',
        image: '/images/featured2.jpg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
      {
        id: 3,
        subTitle: 'items Title',
        image: '/images/featured3.jpeg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
      {
        id: 4,
        subTitle: 'items Title',
        image: '/images/featured4.jpeg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
      {
        id: 5,
        subTitle: 'items Title',
        image: '/images/featured5.jpeg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
      {
        id: 6,
        subTitle: 'items Title',
        image: '/images/featured2.jpg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
      {
        id: 7,
        subTitle: 'items Title',
        image: '/images/featured4.jpeg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
      {
        id: 8,
        subTitle: 'items Title',
        image: '/images/featured5.jpeg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
      {
        id: 9,
        subTitle: 'items Title',
        image: '/images/featured3.jpeg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
      {
        id: 10,
        subTitle: 'items Title',
        image: '/images/featured4.jpeg',
        newPrice: '$33.00',
        oldPrice: '$50.00',
      },
    ],
  },
  {
    id: 7,
    title: 'Mouse Electronics',
  },
  {
    id: 8,
    title: 'Jewelry Watches',
  },
];
